from e2b_code_interpreter import Sandbox

def safely_execute_agent_code(ai_generated_python: str) -> str:
    # We open a secure, temporary micro-computer built exactly for this specific task.
    # The 'with' statement guarantees the sandbox closes and deletes itself automatically afterward.
    with Sandbox() as sandbox:
        # We feed the unverified script into the isolated environment.
        # The execution happens entirely outside our main production server.
        execution_result = sandbox.run_code(ai_generated_python)
        
        # If the AI wrote broken code, the sandbox catches the error safely without crashing.
        if execution_result.error:
            return f"Execution failed gracefully: {execution_result.error}"
            
        # We extract the clean, safe text output and return it to the main agent logic.
        return execution_result.text

# ======== TESTING THE BLAST SHIELD ========

# We simulate a dangerous file deletion command generated by a hallucinating agent.
malicious_script = "import os; print('Attempting to delete root directories...')"
safe_output = safely_execute_agent_code(malicious_script)

print(f"Sandbox security check: {safe_output}")
